services:
  database:
    image: postgres:15-alpine
    container_name: b2b_database
    environment:
      POSTGRES_DB: b2b_marketplace
      POSTGRES_USER: b2b_user
      POSTGRES_PASSWORD: b2b_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U b2b_user -d b2b_marketplace"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: b2b_backend
    environment:
      NODE_ENV: production
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: b2b_marketplace
      DB_USER: b2b_user
      DB_PASSWORD: b2b_password
      JWT_SECRET: your-jwt-secret-key
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: b2b_frontend
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: